apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  default.conf: |
    upstream backend {
      server backend-service:5000;
    }
    server {
        
        listen 80;
        server_name localhost;

        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
    
        location /api {
          allow all;
          proxy_pass http://backend/;
        }

        location /health {
          proxy_pass http://backend/health;
        }
    
        location /ready {
          proxy_pass http://backend/ready;
        }
    }
