apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    {{- include "my-web-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "my-web-app.name" . }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    {{- include "my-web-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "my-web-app.name" . }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
